"""AI Reports service.

Builds a financial snapshot from the user's tracked data and asks an LLM (Groq
via LangChain) to write a fixed-section report. If the LLM is unavailable or the
key is missing, falls back to a rule-based report so the endpoint never fails.
"""
import logging
import os

from sqlalchemy.orm import Session

import models
import schemas
from services.summaries import compute_asset_summary, compute_expense_summary
from services import money

logger = logging.getLogger(__name__)

GROQ_MODEL = "llama-3.3-70b-versatile"

DISCLAIMER = (
    "Penny is not a registered investment adviser. This report is generated by an "
    "AI model for informational purposes only and is not financial advice."
)

REPORT_TYPE_FOCUS = {
    "spending": "where the money goes and how to spend smarter",
    "networth": "asset mix, concentration risk, and growing net worth",
    "savings": "raising the monthly savings rate with concrete steps",
    "investing": "a sensible allocation for the user's risk profile and horizon",
}

SYSTEM_PROMPT = """You are Penny, a friendly, practical personal-finance assistant for an Indian audience.
You are given a JSON snapshot of ONE user's finances (currency, assets, spending, salary, loans, net worth and profile).
Write a concise report focused on: {focus}.

Rules:
- Produce EXACTLY four sections, in this order, with these keys:
  1. key="summary"      title="Summary"
  2. key="overspending" title="Where you overspent"
  3. key="cut_costs"    title="Where to cut costs"
  4. key="grow_savings" title="Ways to grow savings & net worth"
- Ground every claim in the real numbers from the snapshot. Quote actual figures in the user's currency.
- Be specific and actionable; prefer concrete amounts and percentages over generic advice.
- Tailor advice to the user's profile: risk appetite, time horizon, dependents, monthly savings target.
- Use the user's goals (profile.goals). Each goal has a term: "short" (near-term) or "long" (multi-year).
  In "grow_savings", address short-term goals with immediate steps and long-term goals with a multi-year
  plan, referencing each goal by name. If there are no goals, suggest setting one or two.
- If data is sparse, say so plainly and suggest what to track next.
- Do NOT invent transactions, holdings, or numbers that are not in the snapshot.
- Do NOT promise returns or give registered investment advice. Keep a helpful, non-prescriptive tone.
"""


def build_snapshot(db: Session, user: models.User) -> dict:
    """Assemble the exact figures the user sees on screen, plus their profile."""
    assets = compute_asset_summary(db, user)
    expenses = compute_expense_summary(db, user)
    emi_total = assets.emi_total
    salary = money.to_display(user.monthly_salary or 0.0, user) or 0.0  # base -> display
    net_worth = assets.total + salary - expenses.total - emi_total

    return {
        "currency": user.currency,
        "net_worth": round(net_worth, 2),
        "monthly_salary": salary,
        "assets": {
            "total_excluding_loans": assets.total,
            "by_category": [
                {"category": c.category, "total": c.total, "pct": c.pct} for c in assets.by_category
            ],
            "monthly_emi_total": emi_total,
        },
        "expenses_this_month": {
            "total": expenses.total,
            "transactions": expenses.count,
            "by_category": [
                {"category": c.category, "total": c.total, "pct": c.pct} for c in expenses.by_category
            ],
            "last_6_months": [{"month": m.month, "total": m.total} for m in expenses.monthly],
        },
        "profile": {
            "risk_appetite": user.risk_appetite,
            "monthly_savings_target": user.monthly_savings_target,
            "time_horizon_years": user.time_horizon_years,
            "dependents": user.dependents,
            "goals": user.goals or [],
        },
    }


def _generate_with_llm(snapshot: dict, report_type: str) -> schemas.ReportPayload:
    """Call Groq via LangChain and return the structured report. Raises on failure."""
    import json

    from langchain_groq import ChatGroq

    focus = REPORT_TYPE_FOCUS.get(report_type, "the user's overall finances")
    llm = ChatGroq(model=GROQ_MODEL, temperature=0.4, api_key=os.environ["GROQ_API_KEY"])
    structured = llm.with_structured_output(schemas.ReportPayload)
    result = structured.invoke(
        [
            ("system", SYSTEM_PROMPT.format(focus=focus)),
            ("human", f"Here is the user's financial snapshot as JSON:\n{json.dumps(snapshot, indent=2)}"),
        ]
    )
    return result


def _heuristic_report(snapshot: dict) -> schemas.ReportPayload:
    """Rule-based fallback used when the LLM is unavailable."""
    cur = snapshot["currency"]
    exp = snapshot["expenses_this_month"]
    top = exp["by_category"][0] if exp["by_category"] else None
    nw = snapshot["net_worth"]

    def money(v: float) -> str:
        return f"{cur} {v:,.0f}"

    summary = schemas.ReportSection(
        key="summary",
        title="Summary",
        body=(
            f"Your net worth is {money(nw)}. This month you spent {money(exp['total'])} "
            f"across {exp['transactions']} transactions, against monthly income of "
            f"{money(snapshot['monthly_salary'])}."
        ),
        bullets=[],
    )
    overspending = schemas.ReportSection(
        key="overspending",
        title="Where you overspent",
        body=(
            f"{top['category'].title()} is your largest category at {top['pct']}% "
            f"({money(top['total'])})." if top else "No expenses logged this month yet."
        ),
        bullets=([f"Watch {top['category']} — it's over a third of spending." ] if top and top["pct"] > 35 else []),
    )
    cut_costs = schemas.ReportSection(
        key="cut_costs",
        title="Where to cut costs",
        body="Trimming your top discretionary category toward 20% of spending is the quickest win.",
        bullets=["Review subscriptions and recurring charges.", "Set a category budget for next month."],
    )
    grow = schemas.ReportSection(
        key="grow_savings",
        title="Ways to grow savings & net worth",
        body="Automate savings on payday and keep an emergency fund of 3–6 months of expenses.",
        bullets=["Start a monthly SIP into index funds.", "Build an emergency fund first."],
    )
    return schemas.ReportPayload(sections=[summary, overspending, cut_costs, grow])


def generate_report(snapshot: dict, report_type: str) -> tuple[schemas.ReportPayload, str]:
    """Return (payload, model_id). Falls back to heuristics on any LLM failure."""
    if not os.getenv("GROQ_API_KEY"):
        logger.info("GROQ_API_KEY not set — using heuristic report")
        return _heuristic_report(snapshot), "heuristic"
    try:
        return _generate_with_llm(snapshot, report_type), GROQ_MODEL
    except Exception as exc:  # noqa: BLE001 — never fail the request on LLM error
        logger.warning("LLM report generation failed, falling back to heuristic: %s", exc)
        return _heuristic_report(snapshot), "heuristic"
